<?php
/**
	Contact List Element

	Draws the standard table of Contacts

	@package Edoceo Imperium
*/

echo '<table>';
echo '<tr>';
echo '<th>&nbsp;</th>';
echo '<th>Name</th>';
echo '<th>Phone</th>';
echo '<th>Email</th>';
echo '</tr>';

foreach ($this->list as $item) {
    echo '<tr class="rero ' . $item->kind . '">';
    // Show Contact, if none show Name
    switch (strtolower($item->kind)) {
    case 'company':
        echo '<td>' . img('/silk/1.3/building.png',$this->kind) . '</td>';
        break;
    case 'person':
        echo '<td>' . img('/silk/1.3/user_green.png',$this->kind) . '</td>';
        break;
    case 'vendor':
        echo '<td>' . img('/silk/1.3/lorry.png',$this->kind) . '</td>';
        break;
    default:
        echo '<td>' . $item->kind . '</td>';
    }
    echo '<td>' . $this->link('/contact/view?c='.$item->id, $item->name) . '</td>';
    echo '<td>' . $this->partial('../elements/stub-channel.phtml',array('data'=>$item->phone)) . '</td>';
    echo '<td>' . $this->partial('../elements/stub-channel.phtml',array('data'=>$item->email)) . '</td>';
    echo '</tr>';
}

echo '</table>';
