<?php
/**
	Contact Address List Element

	Displays Table of Contact Addresses

	@copyright	2008 Edoceo, Inc
  @package    edoceo-imperium
	@link       http://imperium.edoceo.com
	@since      File available since Release 1013
*/


echo '<table>';
foreach ($this->list as $item) {
	echo '<tr class="rero">';
	$link = $this->link('/contact/address?id=' . $item->id, $item->kind);
	echo '<td>' . $link . '</td>';
	echo '<td>' . $item->__toString() . '</td>';
	echo '<td><a class="fancybox-media" href="http://maps.google.com/maps?q=' . urlencode($item->__toString()) . '">';
	echo img('/tango/24x24/actions/system-search.png','Map');
	echo '</a></td>';
	echo '</tr>';
}
echo '</table>';
