<?php
/**
	Object History View Element

	Used by Invoice and Work Order
*/

if ( (empty($this->list)) || (!is_array($this->list)) || (count($this->list) == 0) ) {
    return;
}

echo '<h2 style="clear:both;">History';
if ( (!empty($this->ajax)) && ($this->ajax == true) ) {
    // Make Link to Popup Object History
    // echo ' <span class="s">[ <a class="fb" href="' . $this->link('/index/diff?object=') . '">View History</a> ]</span>';
}
echo '</h2>';

echo '<table>';
echo '<tr><th>Date</th><th>Field</th><th>Old Value</th><th>&nbsp;</th><th>New Value</th></tr>';

foreach ($this->list as $item) {

    if (empty($item->v0)) $item->v0 = '[null]';

	echo '<tr class="rero">';
	echo '<td class="c">' . ImperiumView::niceDate($item->ctime) . '</td>';
	switch ($item->f) {
	case '-Note-': // Special Case
	    echo '<td colspan="4">' . html($item->v0) . '</td>';
	    break;
	default:
        echo '<td>' . $item->f . '</td>';
        // Old -> New
        echo '<td>' .  $item->v0 . '</td>';
        if (!empty($item->v1)) {
            echo '<td>&raquo;</td>';
            echo '<td>' . $item->v1 . '</td>';
        }
    }
	echo '</tr>';
}
echo '</table>';
