<?php
/**
    @file
    @brief File List Element: Draws a table-list of Notes
*/

if (empty($this->list)) {
    return(0);
}
if (count($this->list)==0) {
    return(0);
}

echo '<h2>Files';
// echo ' <span class="s">[';
// echo ' <a onclick="$(\'#note-list\').toggle(); return false;">View</a> ';
// echo ' <a onclick="$(\'#note-edit\').load(\'' . $this->page . '\').focus(); return false;" href="' . $this->page . '">';
// echo img('/silk/1.3/note_add.png','Add Note');
// echo '</a> ';
// echo ']</span>';
echo '</h2>';
echo '<div id="file-edit"></div>';
echo '<div id="file-list">';

echo '<table>';
echo '<tr><th colspan="2">Name</th><th>Size</th><th>Kind</th></tr>';

foreach ($this->list as $f) {

    $mime = Base_File::mimeInfo($f->kind);

    echo '<tr class="rero">';
    echo '<td>' . img($mime['icon'],$mime['note']) . '</td>';
    echo '<td>' . $this->link('/file/view?id=' . $f->id,$this->escape($f->name)) . '</td>';
    echo '<td class="r">' . $this->escape( ImperiumView::niceSize($f->size) ) . '</td>';
    echo '<td class="r">' . $this->escape($mime['name']) . '</td>';
    // echo '<td>' . $this->link('/file/render/' . $f->id,   img('/tango/24x24/actions/edit-find.png','Render') ) . '</td>';
    echo '<td>' . $this->link('/file/download?id=' . $f->id, img('/tango/24x24/actions/document-save.png','Download') ) . '</td>';
    echo '</tr>';

}

echo '</table>';
