<?php
/**
    Stub Channel
    Draws a Link and some pretty images to a channel

*/

if (empty($this->data)) {
    return;
}

// Just a String? Promot to Object
if (is_string($this->data)) {
    $x = $this->data;
    $this->data = new stdClass();
    $this->data->id = null;
    $this->data->name = null;
    $this->data->data = $x;
    if (preg_match('/[\w\-]+@[\w\-]+\.\w+/',$x)) {
        $this->data->kind = ContactChannel::EMAIL;
    } else {
        $this->data->kind = ContactChannel::PHONE;
    }
}

$id = crc32(serialize($this->data));

// $buf = ContactChannel::$kind_list[$cc->kind];
$html = "\n";
if (strlen($this->data->name)) {
    $html.= $this->data->name . ': ';
}

$edit_link = $this->link('/contact.channel/view?id=' . $this->data->id);

switch ($this->data->kind) {
case ContactChannel::PHONE:
case ContactChannel::FAX:

    $f = $this->data->data;
    if (preg_match('/[a-z]+/',$this->data->data)) {
        // Ignore
    } else {
        // No Letters
        $n = preg_replace('/[^\d]/',null,$this->data->data);
        $ext = null;

        if (empty($n)) {
            return null;
        }

        // $image = img('/silk/1.3/telephone_go.png','Call');

        // if (strpos($number,'x')!==false) {
        //     list($number,$ext) = explode('x',$number);
        // }

        // US format
        if (strlen($n)==10) {
            $n = "1$n";
            $f = trim(substr($n,1,3) . '.' . substr($n,4,3) . '.' . substr($n,7));
        } else {
            $f = trim($this->data->data);
        }

        if (strlen($n) == 0) $n = 'Empty';
        if (strlen($f) == 0) $f = $n;

        $f .= (strlen($ext) ? " x $ext" : null);
    }

    $html.= sprintf('<a href="tel://%s">%s</a>',preg_replace('/[^\d]/',null,$this->data->data),$f);

    if (!empty($this->data->id)) {

        $i = img('/silk/1.3/telephone_edit.png','Edit Telephone Number');

        $html.= '<a class="fb" href="' . $edit_link . '">';
        $html.= $i;
        $html.= '</a>';
    }

    // echo '&nbsp;<a href='sip:$n'>$image</a>';

    //echo "<script type=\"text/javascript\">\n";
    //echo "$(document).ready(function() {\n";
    //echo "$('#ch$id').fancybox({'height':'20%'});\n"; // ,'titleShow':false,'width':'60%'});\n";
    //echo "});</script>\n";
    //echo '<div id="' . sprintf('phone-%x',$id) . '" style="display:none;font-size:28pt;">';
    //echo $buf . '<br>' . $f;
    //echo '</div>';

    // $buf.= $this->link('/contact.channel/view?id='.$this->data->id,$phone_img);
    break;
case ContactChannel::EMAIL:
    //$email_img = img('/silk/1.3/email_edit.png','Edit Email');
    //$image = img('/silk/1.3/email_go.png','Email');
    $html = '<a href="' . $this->link('/email/compose?to=' . $this->data->data) .'">';
    $html.= htmlspecialchars($this->data->data);
    $html.= '</a>';
    if (!empty($this->data->id)) {
        $i = img('/silk/1.3/email_edit.png','Edit Email');
        $html.= '<a href="' . $edit_link . '">';
        $html.= $i;
        $html.= '</a>';
    }
    break;
default:
    // $i = img('/silk/1.3/email_edit.png','Edit Email');
    $html.= $this->data->data;
    $html.= '[D]';
    $html.= '<a href="' . $edit_link . '">';
    $html.= '[Edit]';
    $html.= '</a>';
}

echo $html;
