<?php
/**
	Contact View

	Shows the Contact, Company or Vendors information

	@copyright	2008 Edoceo, Inc
  @package    edoceo-imperium
	@link       http://imperium.edoceo.com
	@since      File available since Release 1013
*/


echo '<form action="" method="get">';
echo '<table>';
echo '<tr>';
echo '<td class="b r">Client:</td>';
echo '<td>' . $this->formText('q',$this->Client,array('style'=>'width:30em')) . '</td>';
echo '<td>' . $this->formSubmit('c','Search') . $this->formSubmit('c','Reset') . '</td></tr>';
echo '</table>';
echo '</form>';

if (!empty($this->ContactList)) {
  //Zend_Debug::dump($this->ContactList);
  echo '<h2>Search Results</h2>';
  echo '<form action="" method="post">';
  echo '<table>';
  foreach ($this->ContactList as $x) {

    if (empty($x->address)) {
      $x->address = '- empty -';
    }

    echo '<tr class="rero">';
    echo '<td>' . $this->formCheckbox('address_id[]',$x->address_id) . '</td>';
    echo '<td><a href="' . $this->link('/contact/view?c=' . $x->contact_id) . '">' . $x->name . '</a></td>';
    echo '<td>' . $x->kind . '</td>';
    echo '<td><a href="' . $this->link('/contact/address?id=' . $x->address_id) .'">' . $x->address . '</a></td>';
    //echo '<td>' . $this->formSubmit('add' . $x->address_id,'Add') . '</td>';
    echo '</tr>';
  }
  echo '</table>';
  echo '<div class="bf">' . $this->formSubmit('c','Add Selected') . '</div>';
  echo '</form>';
}

// Existing Labels

if (!empty($this->ContactLabelList)) {

  echo '<h2>Labels to Print</h2>';
  echo '<form action="" method="post">';
  echo '<table>';
  foreach ($this->ContactLabelList as $x) {

    if (empty($x->address)) {
      $x->address = '- empty -';
    }

    echo '<tr class="rero">';
    echo '<td>' . $this->formCheckbox('address_id[]',$x->address_id) . '</td>';
    echo '<td><a href="' . $this->link('/contact/view?id=' . $x->contact_id) . '">' . $x->name . '</a></td>';
    echo '<td>' . $x->kind . '</td>';
    echo '<td><a href="' . $this->link('/contact/address?id=' . $x->address_id) .'">' . $x->address . '</a></td>';
    //echo '<td>' . $this->formSubmit('add' . $x->address_id,'Add') . '</td>';
    echo '</tr>';
  }
  echo '</table>';

  $list = array(
    '5160' => 'Avery 5160/Office Max 99053 - 30 1x2.625',
  );
  echo '<form action="" method="post">';
  echo '<table>';
  echo '<tr>';
  echo '<td>' . $this->formSelect('page',null,null,$list) . '</td>'; 
  echo '<td>' . $this->formSubmit('c','Print') . '</td>';
  echo '</tr>';
  echo '</table>';
  echo '</form>';
}
//Zend_Debug::dump($this->ContactLabelList);
