
-- Base Data for the System
-- $Id: 50-data.sql 1073 2008-07-19 22:56:28Z david.busby $

insert into auth_user (id,username,password,active) values (1,'root','root','t');
insert into auth_user (id,username,password,active) values (2,'demo','demo','t');

-- Base Accounts

INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (1,'true','Business Checking', NULL, 0.00, NULL, NULL, 69904, 100, '100', 'Asset', '100 - Asset:Business Checking', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (2,'true','Business Savings', NULL, 0.00, NULL, NULL, 69888, 110, '110', 'Asset', '110 - Asset:Business Savings', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (3,'true','Miscellaneous Liabilities', NULL, 0.00, NULL, NULL, 135168, 200, '200', 'Liability', '200 - Liability:Miscellaneous Liabilities', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (4,'true','Sales Taxes', NULL, 0.00, NULL, NULL, 139264, 220, '220', 'Liability', '220 - Liability:Sales Taxes', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (5,'true','Income Summary', NULL, 0.00, NULL, NULL, 73728, 191, '191', 'Asset', '191 - Asset:Income Summary', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (6,'true','Accounts Receivable', NULL, 0.00, 200, NULL, 70656, 130, '130', 'Asset', '130 - Asset:Accounts Receivable', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (7,'true','Inbound Cash', NULL, 0.00, NULL, NULL, 73728, 190, '190', 'Asset', '190 - Asset:Inbound Cash', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (8,'true','Owners Capital', NULL, 0.00, NULL, NULL, 266240, 510, '510', 'Equity', '510 - Equity:Owners Capital', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (9,'true','Miscellaneous Revenue', NULL, 0.00, NULL, NULL, 1056768, 390, '390', 'Revenue', '390 - Revenue:Miscellaneous Revenue', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (10,'true','Interest Revenue', NULL, 0.00, NULL, NULL, 1056768, 350, '350', 'Revenue', '350 - Revenue:Interest Revenue', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (11,'true','Invoice Revenue', NULL, 0.00, 300, NULL, 1056768, 300, '300', 'Revenue', '300 - Revenue:Invoice Revenue', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (12,'true','Miscellaneous', 21, 0.00, NULL, NULL, 2101248, 900, '420.900', 'Expense', '420.900 - Expense:Miscellaneous', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (13,'true','Development Services', NULL, 0.00, NULL, NULL, 2101248, 460, '460', 'Expense', '460 - Expense:Development Services', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (14,'true','Developers', 84, 0.00, NULL, NULL, 2101248, 100, '460.100', 'Expense', '460.100 - Expense:Developers', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (15,'true','Miscellaneous', 17, 0.00, NULL, NULL, 2101248, 900, '450.900', 'Expense', '450.900 - Expense:Miscellaneous', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (16,'true','Communications Services', NULL, 0.00, NULL, NULL, 2105344, 430, '430', 'Expense', '430 - Expense:Communications Services', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (17,'true','Travel and Transportation', NULL, 0.00, NULL, NULL, 2105344, 450, '450', 'Expense', '450 - Expense:Travel and Transportation', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (18,'true','Business Services', NULL, 0.00, NULL, NULL, 2105344, 400, '400', 'Expense', '400 - Expense:Business Services', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (19,'true','Internet Services', NULL, 0.00, NULL, NULL, 2105344, 420, '420', 'Expense', '420 - Expense:Internet Services', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (20,'true','Miscellaneous', 19, 0.00, NULL, NULL, 2101248, 900, '400.900', 'Expense', '400.900 - Expense:Miscellaneous', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (21,'true','Equipment', NULL, 0.00, NULL, NULL, 2105344, 401, '401', 'Expense', '401 - Expense:Equipment', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (22,'true','Meals', 17, 0.00, NULL, NULL, 2105344, 300, '450.300', 'Expense', '450.300 - Expense:Meals', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (23,'true','Auto and Fuel', 17, 0.00, NULL, NULL, 2101248, 200, '450.200', 'Expense', '450.200 - Expense:Auto and Fuel', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (24,'true','Advertising', 19, 0.00, NULL, NULL, 2105344, 300, '400.300', 'Expense', '400.300 - Expense:Advertising', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (25,'true','Parking', 17, 0.00, NULL, NULL, 2101248, 100, '450.100', 'Expense', '450.100 - Expense:Parking', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (26,'true','Miscellaneous Expense', NULL, 91.00, NULL, NULL, 2105344, 490, '490', 'Expense', '490 - Expense:Miscellaneous Expense', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (27,'true','Misc', 2, NULL, NULL, NULL, 70656, 999, '130.999', 'Asset', '130.999 - Asset:Misc', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (28,'true','Client Ledgers', 2, NULL, NULL, NULL, 70656, 600, '600', null, '600 - Sub: Client Ledgers', NULL);
INSERT INTO account (id,active, name, parent_id, balance, link_to, link_id, flag, code, full_code, kind, full_name, account_tax_line_id) VALUES (29,'true','Vendor Ledgers', 2, NULL, NULL, NULL, 70656, 700, '700', null, '700 - Sub: Vendor Ledgers', NULL);

select setval('account_id_seq',(select id from account order by id desc limit 1),true);

--
-- Base Object Descriptors
--

INSERT INTO base_object (id, name, stub, note, path, link) VALUES (100, 'Account', 'account', NULL, 'account', 'account');
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (102, 'AccountLedgerEntry', 'accountledgerentry', NULL, 'accountledgerentry', 'account_ledger_entry');
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (150, 'AccountWizardJournal', 'accountwizardjournal', NULL, 'accountwizardjournal', 'account_wizard_journal');
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (151, 'AccountWizardLedgerEntry', 'accountwizardledgerentry', NULL, 'accountwizardledgerentry', 'account_wizard_ledger');
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (6564, 'ImperiumUser', 'imperiumuser', NULL, 'imperiumuser', 'auth_user');
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (300, 'Invoice', 'invoice', NULL, 'invoice', 'invoice');
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (6170, 'Manual', 'manual', NULL, 'manual', NULL);
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (9802, 'Timesheet', 'timesheet', NULL, 'timesheet', 'timesheet');
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (301, 'InvoiceItem', 'invoiceitem', NULL, 'invoice.item/view/id/%d', 'invoice_item');
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (101, 'AccountJournalEntry', 'accountjournalentry', NULL, 'account/transaction/view/id/%d', 'account_journal');
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (201, 'ContactAddress', 'contactaddress', NULL, 'contact.address/view/id/%d', 'contact_address');
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (202, 'ContactChannel', 'contactchannel', NULL, 'contact.channel/view/id/%d', 'contact_channel');
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (401, 'WorkOrderItem', 'workorderitem', NULL, 'workorder.item/view/id/%d', 'workorder_item');
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (600, 'Note', 'note', NULL, 'note/view/id/%d', 'base_note');
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (5005, 'File', 'file', 'Files can be attached to any other object', 'file/view/id/%d', 'base_file');
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (8750, 'Todo', 'todo', NULL, 'todo/view/id/%d', 'base_todo');
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (400, 'WorkOrder', 'workorder', NULL, 'workorder/view/id/%d', 'workorder');
INSERT INTO base_object (id, name, stub, note, path, link) VALUES (200, 'Contact', 'contact', NULL, 'contact/view/id/%d', 'contact');

-- Units of Measurement for WorkOrder or Invoice Items
INSERT INTO base_unit (id, name) VALUES ('ea','Each');
INSERT INTO base_unit (id, name) VALUES ('ft','Foot');
INSERT INTO base_unit (id, name) VALUES ('g','Gram');
INSERT INTO base_unit (id, name) VALUES ('GiB','Gigabyte');
INSERT INTO base_unit (id, name) VALUES ('hr','Hour');
INSERT INTO base_unit (id, name) VALUES ('km','Kilometer');
INSERT INTO base_unit (id, name) VALUES ('lb','Pound');
INSERT INTO base_unit (id, name) VALUES ('MiB','Megabyte');
INSERT INTO base_unit (id, name) VALUES ('m','Meter');
INSERT INTO base_unit (id, name) VALUES ('mi','Mile');
INSERT INTO base_unit (id, name) VALUES ('mo','Month');
INSERT INTO base_unit (id, name) VALUES ('oz','Ounce');
INSERT INTO base_unit (id, name) VALUES ('qt','Quarter');
INSERT INTO base_unit (id, name) VALUES ('yd','Yard');
INSERT INTO base_unit (id, name) VALUES ('yr','Year');

-- Countries
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (1, 'AF', 'AFG', 'Afghanistan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (2, 'AX', 'ALA', 'Åland Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (4, 'DZ', 'DZA', 'Algeria (el Djazaïr)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (3, 'AL', 'ALB', 'Albania', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (5, 'AS', 'ASM', 'American Samoa', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (6, 'AD', 'AND', 'Andorra', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (7, 'AO', 'AGO', 'Angola', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (8, 'AI', 'AIA', 'Anguilla', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (9, 'AQ', 'ATA', 'Antarctica', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (10, 'AG', 'ATG', 'Antigua And Barbuda', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (11, 'AR', 'ARG', 'Argentina', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (12, 'AM', 'ARM', 'Armenia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (13, 'AW', 'ABW', 'Aruba', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (14, 'AU', 'AUS', 'Australia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (15, 'AT', 'AUT', 'Austria', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (16, 'AZ', 'AZE', 'Azerbaijan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (17, 'BS', 'BHS', 'Bahamas', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (18, 'BH', 'BHR', 'Bahrain', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (19, 'BD', 'BGD', 'Bangladesh', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (20, 'BB', 'BRB', 'Barbados', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (21, 'BY', 'BLR', 'Belarus', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (22, 'BE', 'BEL', 'Belgium', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (23, 'BZ', 'BLZ', 'Belize', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (24, 'BJ', 'BEN', 'Benin', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (25, 'BM', 'BMU', 'Bermuda', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (26, 'BT', 'BTN', 'Bhutan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (27, 'BO', 'BOL', 'Bolivia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (28, 'BA', 'BIH', 'Bosnia And Herzegovina', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (29, 'BW', 'BWA', 'Botswana', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (30, 'BV', 'BVT', 'Bouvet Island', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (31, 'BR', 'BRA', 'Brazil', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (32, 'IO', 'IOT', 'British Indian Ocean Territory', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (33, 'BN', 'BRN', 'Brunei Darussalam', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (34, 'BG', 'BGR', 'Bulgaria', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (35, 'BF', 'BFA', 'Burkina Faso', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (36, 'BI', 'BDI', 'Burundi', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (37, 'KH', 'KHM', 'Cambodia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (38, 'CM', 'CMR', 'Cameroon', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (39, 'CA', 'CAN', 'Canada', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (40, 'CV', 'CPV', 'Cape Verde', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (41, 'KY', 'CYM', 'Cayman Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (42, 'CF', 'CAF', 'Central African Republic', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (43, 'TD', 'TCD', 'Chad (tchad)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (44, 'CL', 'CHL', 'Chile', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (45, 'CN', 'CHN', 'China', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (46, 'CX', 'CXR', 'Christmas Island', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (47, 'CC', 'CCK', 'Cocos (keeling) Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (48, 'CO', 'COL', 'Colombia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (49, 'KM', 'COM', 'Comoros', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (50, 'CG', 'COG', 'Congo, Republic Of', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (51, 'CD', 'COD', 'Congo, The Democratic Republic Of The (formerly Zaire)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (52, 'CK', 'COK', 'Cook Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (53, 'CR', 'CRI', 'Costa Rica', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (54, 'CI', 'CIV', 'CÔte D''ivoire (ivory Coast)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (55, 'HR', 'HRV', 'Croatia (hrvatska)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (56, 'CU', 'CUB', 'Cuba', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (57, 'CY', 'CYP', 'Cyprus', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (58, 'CZ', 'CZE', 'Czech Republic', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (59, 'DK', 'DNK', 'Denmark', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (60, 'DJ', 'DJI', 'Djibouti', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (61, 'DM', 'DMA', 'Dominica', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (62, 'DO', 'DOM', 'Dominican Republic', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (63, 'EC', 'ECU', 'Ecuador', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (64, 'EG', 'EGY', 'Egypt', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (65, 'SV', 'SLV', 'El Salvador', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (66, 'GQ', 'GNQ', 'Equatorial Guinea', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (67, 'ER', 'ERI', 'Eritrea', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (68, 'EE', 'EST', 'Estonia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (69, 'ET', 'ETH', 'Ethiopia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (70, 'FO', 'FRO', 'Faeroe Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (71, 'FK', 'FLK', 'Falkland Islands (malvinas)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (72, 'FJ', 'FJI', 'Fiji', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (73, 'FI', 'FIN', 'Finland', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (74, 'FR', 'FRA', 'France', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (75, 'GF', 'GUF', 'French Guiana', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (76, 'PF', 'PYF', 'French Polynesia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (77, 'TF', 'ATF', 'French Southern Territories', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (78, 'GA', 'GAB', 'Gabon', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (79, 'GM', 'GMB', 'Gambia, The', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (80, 'GE', 'GEO', 'Georgia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (81, 'DE', 'DEU', 'Germany (deutschland)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (82, 'GH', 'GHA', 'Ghana', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (83, 'GI', 'GIB', 'Gibraltar', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (84, 'GB', 'GBR', 'Great Britain', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (85, 'GR', 'GRC', 'Greece', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (86, 'GL', 'GRL', 'Greenland', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (87, 'GD', 'GRD', 'Grenada', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (88, 'GP', 'GLP', 'Guadeloupe', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (89, 'GU', 'GUM', 'Guam', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (90, 'GT', 'GTM', 'Guatemala', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (91, 'GN', 'GIN', 'Guinea', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (92, 'GW', 'GNB', 'Guinea-bissau', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (93, 'GY', 'GUY', 'Guyana', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (94, 'HT', 'HTI', 'Haiti', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (95, 'HM', 'HMD', 'Heard Island And Mcdonald Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (96, 'HN', 'HND', 'Honduras', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (97, 'HK', 'HKG', 'Hong Kong (special Administrative Region Of China)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (98, 'HU', 'HUN', 'Hungary', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (99, 'IS', 'ISL', 'Iceland', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (100, 'IN', 'IND', 'India', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (101, 'ID', 'IDN', 'Indonesia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (102, 'IR', 'IRN', 'Iran (islamic Republic Of Iran)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (103, 'IQ', 'IRQ', 'Iraq', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (104, 'IE', 'IRL', 'Ireland', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (105, 'IL', 'ISR', 'Israel', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (106, 'IT', 'ITA', 'Italy', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (107, 'JM', 'JAM', 'Jamaica', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (108, 'JP', 'JPN', 'Japan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (109, 'JO', 'JOR', 'Jordan (hashemite Kingdom Of Jordan)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (110, 'KZ', 'KAZ', 'Kazakhstan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (111, 'KE', 'KEN', 'Kenya', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (112, 'KI', 'KIR', 'Kiribati', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (113, 'KP', 'PRK', 'Korea (democratic Peoples Republic Of [north]          Korea)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (114, 'KR', 'KOR', 'Korea (republic Of [south] Korea)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (115, 'KW', 'KWT', 'Kuwait', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (116, 'KG', 'KGZ', 'Kyrgyzstan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (117, 'LA', 'LAO', 'Lao People''s Democratic Republic', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (118, 'LV', 'LVA', 'Latvia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (119, 'LB', 'LBN', 'Lebanon', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (120, 'LS', 'LSO', 'Lesotho', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (121, 'LR', 'LBR', 'Liberia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (122, 'LY', 'LBY', 'Libya (libyan Arab Jamahirya)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (123, 'LI', 'LIE', 'Liechtenstein (fürstentum Liechtenstein)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (124, 'LT', 'LTU', 'Lithuania', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (125, 'LU', 'LUX', 'Luxembourg', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (126, 'MO', 'MAC', 'Macao (special Administrative Region Of China)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (127, 'MK', 'MKD', 'Macedonia (former Yugoslav Republic Of Macedonia)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (128, 'MG', 'MDG', 'Madagascar', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (129, 'MW', 'MWI', 'Malawi', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (130, 'MY', 'MYS', 'Malaysia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (131, 'MV', 'MDV', 'Maldives', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (132, 'ML', 'MLI', 'Mali', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (133, 'MT', 'MLT', 'Malta', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (134, 'MH', 'MHL', 'Marshall Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (135, 'MQ', 'MTQ', 'Martinique', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (136, 'MR', 'MRT', 'Mauritania', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (137, 'MU', 'MUS', 'Mauritius', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (138, 'YT', 'MYT', 'Mayotte', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (139, 'MX', 'MEX', 'Mexico', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (140, 'FM', 'FSM', 'Micronesia (federated States Of Micronesia)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (141, 'MD', 'MDA', 'Moldova', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (142, 'MC', 'MCO', 'Monaco', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (143, 'MN', 'MNG', 'Mongolia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (144, 'MS', 'MSR', 'Montserrat', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (145, 'MA', 'MAR', 'Morocco', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (146, 'MZ', 'MOZ', 'Mozambique (moçambique)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (147, 'MM', 'MMR', 'Myanmar (formerly Burma)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (148, 'NA', 'NAM', 'Namibia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (149, 'NR', 'NRU', 'Nauru', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (150, 'NP', 'NPL', 'Nepal', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (151, 'NL', 'NLD', 'Netherlands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (152, 'AN', 'ANT', 'Netherlands Antilles', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (153, 'NC', 'NCL', 'New Caledonia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (154, 'NZ', 'NZL', 'New Zealand', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (155, 'NI', 'NIC', 'Nicaragua', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (156, 'NE', 'NER', 'Niger', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (157, 'NG', 'NGA', 'Nigeria', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (158, 'NU', 'NIU', 'Niue', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (159, 'NF', 'NFK', 'Norfolk Island', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (160, 'MP', 'MNP', 'Northern Mariana Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (161, 'NO', 'NOR', 'Norway', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (162, 'OM', 'OMN', 'Oman', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (163, 'PK', 'PAK', 'Pakistan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (164, 'PW', 'PLW', 'Palau', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (165, 'PS', 'PSE', 'Palestinian Territories', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (166, 'PA', 'PAN', 'Panama', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (167, 'PG', 'PNG', 'Papua New Guinea', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (168, 'PY', 'PRY', 'Paraguay', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (169, 'PE', 'PER', 'Peru', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (170, 'PH', 'PHL', 'Philippines', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (171, 'PN', 'PCN', 'Pitcairn', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (172, 'PL', 'POL', 'Poland', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (173, 'PT', 'PRT', 'Portugal', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (174, 'PR', 'PRI', 'Puerto Rico', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (175, 'QA', 'QAT', 'Qatar', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (176, 'RE', 'REU', 'RÉunion', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (177, 'RO', 'ROU', 'Romania', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (178, 'RU', 'RUS', 'Russian Federation', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (179, 'RW', 'RWA', 'Rwanda', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (180, 'SH', 'SHN', 'Saint Helena', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (181, 'KN', 'KNA', 'Saint Kitts And Nevis', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (182, 'LC', 'LCA', 'Saint Lucia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (183, 'PM', 'SPM', 'Saint Pierre And Miquelon', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (184, 'VC', 'VCT', 'Saint Vincent And The Grenadines', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (185, 'WS', 'WSM', 'Samoa (formerly Western Samoa)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (186, 'SM', 'SMR', 'San Marino (republic Of)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (187, 'ST', 'STP', 'Sao Tome And Principe', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (188, 'SA', 'SAU', 'Saudi Arabia (kingdom Of Saudi Arabia)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (189, 'SN', 'SEN', 'Senegal', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (190, 'CS', 'SCG', 'Serbia And Montenegro (formerly Yugoslavia)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (191, 'SC', 'SYC', 'Seychelles', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (192, 'SL', 'SLE', 'Sierra Leone', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (193, 'SG', 'SGP', 'Singapore', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (194, 'SK', 'SVK', 'Slovakia (slovak Republic)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (195, 'SI', 'SVN', 'Slovenia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (196, 'SB', 'SLB', 'Solomon Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (197, 'SO', 'SOM', 'Somalia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (198, 'ZA', 'ZAF', 'South Africa (zuid Afrika)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (199, 'GS', 'SGS', 'South Georgia And The South Sandwich Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (200, 'ES', 'ESP', 'Spain (españa)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (201, 'LK', 'LKA', 'Sri Lanka', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (202, 'SD', 'SDN', 'Sudan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (203, 'SR', 'SUR', 'Suriname', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (204, 'SJ', 'SJM', 'Svalbard And Jan Mayen', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (205, 'SZ', 'SWZ', 'Swaziland', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (206, 'SE', 'SWE', 'Sweden', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (207, 'CH', 'CHE', 'Switzerland (confederation Of Helvetia)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (208, 'SY', 'SYR', 'Syrian Arab Republic', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (209, 'TW', 'TWN', 'Taiwan ("chinese Taipei" For Ioc)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (210, 'TJ', 'TJK', 'Tajikistan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (211, 'TZ', 'TZA', 'Tanzania', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (212, 'TH', 'THA', 'Thailand', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (213, 'TL', 'TLS', 'Timor-leste (formerly East Timor)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (214, 'TG', 'TGO', 'Togo', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (215, 'TK', 'TKL', 'Tokelau', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (216, 'TO', 'TON', 'Tonga', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (217, 'TT', 'TTO', 'Trinidad And Tobago', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (218, 'TN', 'TUN', 'Tunisia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (219, 'TR', 'TUR', 'Turkey', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (220, 'TM', 'TKM', 'Turkmenistan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (221, 'TC', 'TCA', 'Turks And Caicos Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (222, 'TV', 'TUV', 'Tuvalu', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (223, 'UG', 'UGA', 'Uganda', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (224, 'UA', 'UKR', 'Ukraine', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (225, 'AE', 'ARE', 'United Arab Emirates', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (226, 'GB', 'GBR', 'United Kingdom (great Britain)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (227, 'US', 'USA', 'United States', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (228, 'UM', 'UMI', 'United States Minor Outlying Islands', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (229, 'UY', 'URY', 'Uruguay', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (230, 'UZ', 'UZB', 'Uzbekistan', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (231, 'VU', 'VUT', 'Vanuatu', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (232, 'VA', 'VAT', 'Vatican City (holy See)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (233, 'VE', 'VEN', 'Venezuela', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (234, 'VN', 'VNM', 'Viet Nam', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (235, 'VG', 'VGB', 'Virgin Islands, British', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (236, 'VI', 'VIR', 'Virgin Islands, U.s.', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (237, 'WF', 'WLF', 'Wallis And Futuna', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (238, 'EH', 'ESH', 'Western Sahara (formerly Spanish Sahara)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (239, 'YE', 'YEM', 'Yemen (arab Republic)', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (240, 'ZM', 'ZMB', 'Zambia', NULL);
INSERT INTO base_country (id, iso2, iso3, name_en, name_fr) VALUES (241, 'ZW', 'ZWE', 'Zimbabwe', NULL);

