<?php
/**
    @file
    @brief A Single Column Layout, CSS Dropdown Menus
*/

$layout = $this->layout();

// Convert Controller Specified Array to String
if (is_array($this->title)) {
	$this->title = implode(' &raquo; ',$this->title);
}

echo $this->doctype('HTML5') . "\n";
//echo $html->docType('xhtml11');
echo "<html lang=\"en-us\">\n";
?>
<head>
<title>Imperium: <?php echo $this->title; ?></title>
<?php
// $this->headLink()->appendAlternate('/feed/', 'application/rss+xml', 'RSS Feed');
$this->headLink()->appendStylesheet('//gcdn.org/radix/radix.css');
$this->headLink()->appendStylesheet($this->link('/css/base.css'),'all');
$this->headLink()->appendStylesheet('//gcdn.org/jquery-ui/1.10.2/smoothness.css');

$this->headScript()->appendFile('//gcdn.org/jquery/1.9.1/jquery.js');
$this->headScript()->appendFile('//gcdn.org/jquery-ui/1.10.2/jquery-ui.js');
$this->headScript()->appendFile($this->link('/js/imperium.js'));

// Fancybox
// $this->headLink()->appendStylesheet('//gcdn.org/fancybox/2.1.0/fancybox.css');
// $this->headScript()->appendFile('//gcdn.org/fancybox/2.1.0/fancybox.js');

// Farbastic
// @note if continuing to use colour wheel, use farbtastic from gcdn.org

// Header Output
echo $this->headLink();
echo $this->headScript();

?>
<link href="<?php echo $this->link('/img/imperium-icon.ico') ?>" rel="shortcut icon">
<link href="<?php echo $this->link('/img/imperium-icon.png') ?>" rel="apple-touch-icon">
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes" />
</head>
<body ontouchstart="">

<?php
// Content Header
echo '<header>';
echo '<div id="logo">';
$img = '<img alt="logo" src="' . $_ENV['application']['logo'] . '" />';
echo $this->link('/',$img);
echo '</div>';

echo '<h1>' . $this->title . '</h1>';
if (!empty($this->title_one)) {
    echo '<h2>' . $this->title_one . '</h2>';
}
if (!empty($this->title_two)) {
    echo $this->title_two;
}
// echo ImperiumView::mruDraw();
echo '</header>';

// Menu for Authenticated Users Only
$auth = Zend_Auth::getInstance();
if ($auth->hasIdentity()) {
    echo '<div id="menu">';
    echo $this->render('../elements/menu.phtml');
    echo '<hr /></div>';
}

// Core of Page
echo '<div id="core">';

// Title for Printing Only (po)
echo '<div class="po">';
echo '<h1>' . $this->title . '</h1>';
if (!empty($this->title_one)) {
  echo '<h2>' . $this->title_one . '</h2>';
}
echo '</div>';

echo ImperiumView::drawSessionMessages();

echo $layout->content;

echo '</div>'; // #core

?>

<footer>
<a href="http://imperium.edoceo.com">Imperium</a> &#169; 2001-2012 <a href="http://edoceo.com/">Edoceo, Inc</a> | Valid <a href="http://validator.w3.org/check/referer" rel="nofollow">html</a> &amp; <a href="http://jigsaw.w3.org/css-validator/check/referer" rel="nofollow">css</a>
</footer>

<script type="text/javascript">
$(document).ready(function() {
    // $('input[type=text], textarea').focus(function(e) { this.select(); }).mouseup(function(e){ e.preventDefault(); });
    // $('.fancybox').fancybox();
    $('.ajax-edit').on('click',function(e) {
        // var o = $(this).parent().offset();
        var t = $(this).data('name');
        $('#' + t).load(this.href,function(res,txt,xhr) {
            $('#' + t).addClass('edit-show');
            // $(document).animate({ scrollTop: o.top},'slow');
            // $(document).scrollTop(o.top - 16);
        });
        e.preventDefault();
    });
    $(".star").on("click", star_step );
});
</script>
</body>
</html>
