<?php
/**
    @file
    @brief Handles a Mime Download
*/

header('Cache-Control: private,must-revalidate,max-age=5',true);

if ((!empty($this->send_file)) && (is_file($this->send_file))) {

    $fs = filesize($this->send_file);

    //if (empty($this->force_download)) {
    header('Content-Disposition: attachment; filename="' . $this->name . '"',true);
    //} else {
    //  header('Content-Disposition: inline; filename="' . $this->name . '"',true);
    //}
    header('Content-Length: ' . $fs,true);
    header('Content-Type: ' . $this->mime_type,true);

    $fh = fopen($this->send_file,'r');
    fpassthru($fh);
}