<?php
/**
    @file
    @brief Layout/Theme for PDF Documents
    $Id$
*/

//header('Cache-Control: private,must-revalidate,max-age=5',true);
header('Cache-Control: private',true);
header('Content-Disposition: attachment; filename="' . $this->file->name . '"',true);
//header('Content-Length: ' . $this->file->size,true);
header('Content-Type: application/pdf',true);
header('Expires: 0');
header('Pragma: cache');

echo $this->file->data;
