<?php
/**
	Imperium Config Index View
	Start of the Configuration Pages
*/

echo "<ul>";
echo "<li>" . $this->link('/settings/business','Business Profile') . "</li>\n";
echo "<li>" . $this->link('/settings/profile','User Profile') . "</li>\n";
echo "<li>" . $this->link('/settings/password','Change Password') . "</li>\n";
echo "<li>" . $this->link('/settings/registry','View Regsitry') . "</li>\n";
echo "<li>" . $this->link('/settings/session','View Session') . "</li>\n";
// note: to change the Business Profile edit the settings in APP /config/bootstrap.php
echo "</ul>\n";
echo "<hr />";
echo "<ul>";
echo '<li>' . $this->link('/settings/dashboard','Dashboard') . ' - Configure layout and selection criteria</li>';
echo "<li>" . $this->link('/settings/workorder','Work Orders') . " - Orders from Contacts to perform Work</li>";
echo "<li>" . $this->link('/settings/invoice','Invoices') . " - Invoicing Contacts</li>";
echo '<li>' . $this->link('/settings/accounting','Accounting') . ' - Configure the accounting system.</li>';
//echo "<li>" . $html->link('Purchse Orders','/settings/purchase_orders') . " - Purchase Equipment from Vendors</li>";
//echo "<hr />";
//echo "<ul>";
//echo "<li>" . $this->link('/settings/tags','Tags') . " - Object Tags and Categories</li>\n";
//echo "<li>" . $this->link('/settings/labels','Colour Labels') . " - Colour labels for each Object</li>\n";
//echo "<li><a href='./plugins.php'>Plugins</a> - Frame Based Plugins</li>\n";
//echo "<li><a href='./remember.php'>Remember Me</a> - Configure Imperium to remember you on this computer.</li>";

//if ($session->read('Auth.EdoceoUser.id')==1)
//{
  //echo "</ul>\n";
  //echo "<hr />";
  //echo "<ul>";
  echo "<li>" . $this->link('/settings/users','Users') ."</li>";
	echo "<li>" . $this->link('/selenium','Run Selenum Tests') . "</li>\n";

echo "</ul>\n";

// echo '<h2>Imperium Config</h2>';
// Zend_Debug::dump($_ENV);

// echo '<h2>Imperium Server</h2>';
// Zend_Debug::dump($_SERVER);