<?php
/**
    @file
    @brief Batch Updating Transactions

*/


echo '<form method="post">';
echo '<table>';
echo '<tr><td>Account:</td><td>' . $this->formSelect('account_id',$this->account_id,null,$this->AccountPairList) . "</td></tr>";
echo '<tr>';
echo '<td>From:</td><td>';
echo $this->formText('d0',$this->date_alpha,array('size'=>12));
echo '&nbsp;to&nbsp;';
echo $this->formText('d1',$this->date_omega,array('size'=>12));
echo '</td></tr>';
echo '<tr><td>Kind:</td><td><select name="crdr">';
    echo '<option ' . ($_POST['crdr']=='cr' ? 'selected ' : null) . 'value="cr">Credits</option>';
    echo '<option ' . ($_POST['crdr']=='dr' ? 'selected ' : null) . 'value="dr">Debits</option>';
echo '</select></td></tr>';
echo '<tr><td>Note:</td><td><input name="note" type="text" value="' . $_POST['note'] . '"></td></tr>';
echo '<tr><td colspan="2">';
echo '<input name="exec" type="submit" value="Preview">';
echo '</td></tr>';
echo '</table>';
echo '</form>';

echo '<form method="post">';
echo '<table>';
foreach ($this->LedgerEntryList as $le)
{
	//$date = AppHelper::dateNice($le['date']);
	//$link = '/accounts/journal/entry/'.$le['account_journal_id'];
	
  echo '<tr class="rero">';
  echo '<td class="c">' . $this->link('/account/transaction?id=' . $le->account_journal_id, $le->date) . '</td>';
  echo '<td>' . $le->account_name . '/' . $le->note . '</td>';
  echo sprintf('<td class="c">#%s%s</td>',$le->kind,$le->account_journal_id);
  echo sprintf('<td class="c">%s:%d</td>',$le->link_to,$le->link_id);
  
	if ($le->amount > 0) {
		echo "<td>&nbsp;</td><td class='r'>".number_format($le->amount,2)."</td>";
	} else {
		echo "<td class='r'>".number_format(abs($le->amount),2)."</td><td>&nbsp;</td>";
	}
  //elseif ($view=='m') echo date('D jS',strtotime($je->date));

  if (substr($this->Account->kind,0,5)=='Asset') {
    if ($le->amount < 0) {
      $balance_x += abs($le->amount);
    } else {
      $balance_x -= abs($le->amount);
    }
  } else {
    $balance_x += $le->amount;
  }
  
  echo '<td class="r">' . number_format($balance_x,2) . '</td>';
  echo '</tr>';
	
}
echo '</table>';
echo '<div>';
echo '<input name="exec" type="submit" value="Update">';
echo '</div>';
echo '</form>';