<?php
/**
    @file
    @brief View for reconciling/importing transactions
    @verison $Id$

*/

$this->title = array('Account','Reconcile');

if (empty($_ENV['mode'])) {
    $_ENV['mode'] = 'load';
}

// $this->form('Reconcile',array('action'=>$this->link('/account/reconcile.preview'),'enctype'=>'multipart/form-data','method'=>'post'));
switch ($_ENV['mode']) {
case 'save':
case 'view':

    // View the Pending Transactions
    echo '<form method="post">';
    echo '<table>';
    echo '<tr>';
    echo '<th>#</th>';
    echo '<th>Date</th>';
    echo '<th>Note</th>';
    echo '<th>Account</th>';
    echo '<th>Debit</th>';
    echo '<th>Credit</th>';
    echo '<th>JE</th>';
    echo '</tr>';

    $i = 0;
    $cr = 0;
    $dr = 0;
    foreach ($this->JournalEntryList as $je) {

        $i++;
        $offset_id = $_ENV['offset_account_id'];
        // Pattern Match to Find the Chosen Offseter?

        echo '<tr class="rero">';
        echo '<td class="r">' . $i . '</td>';
        echo '<td class="c"><input name="' . sprintf('je%ddate',$i) . '" size="10" type="text" value="' . $je->date . '"></td>';
        echo '<td><input name="' . sprintf('je%dnote',$i) . '" style="width:384px;" type="text" value="' . $je->note . '"></td>';
        echo '<td>';
        echo $this->formSelect(sprintf('je%daccount_id',$i),$offset_id,null,$this->AccountPairList);
        echo '</td>';
        // echo $this->formText('note',$je->note,array('style'=>'width:25em'));
        // @todo Determine Side, which depends on the Kind of the Account for which side is which
        if (!empty($je->dr)) {
            $dr += floatval($je->dr);
            echo '<td class="r">' . $this->formText(sprintf('je%ddr',$i),number_format($je->dr,2),array('size'=>8)) . '</td>';
            echo '<td>&nbsp;</td>';
        } else {
            $cr += floatval($je->cr);
            echo '<td>&nbsp;</td>';
            echo '<td class="r">' . $this->formText(sprintf('je%dcr',$i),number_format($je->cr,2),array('size'=>8)) . '</td>';
        }
        echo '<td>';
        if ($je->id) {
            echo $this->link('/account/transaction?id=' . $je->id,$je->id);
            echo '<input name="' . sprintf('je%did',$i) . '" type="hidden" value="' . $je->id . '">';
        } else {
            echo '&mdash;';
        }
        echo '</td>';
        echo '</tr>';
    }
    echo '<tr>';
    echo '<td colspan="4">Summary: ' . $this->JournalEntryList[0]->date . ' - ' . $je->date . '</td>';
    echo '<td class="r">' . number_format($dr,2) . '</td>';
    echo '<td class="r">' . number_format($cr,2) . '</td>';
    echo '</table>';
    echo '<div class="cmd">';
    echo '<input name="cmd" type="submit" value="Save">';
    echo '</div>';
    echo '</form>';

    return;

case 'load':
default:
    echo '<form enctype="multipart/form-data" method="post">';
    echo '<fieldset><legend>Step 1 - Choose Account and Data File</legend>';
    echo '<table>';
    echo '<tr><td class="l" title="Account whos transactions are being uploaded">Account:</td><td>' . $this->formSelect('upload_id',$this->Account->id,null,$this->AccountPairList)  . '</td></tr>';
    echo '<tr><td class="l" title="Default off-set account for the transactions, a pending queue for reconciliation">Offset:</td><td>' . $this->formSelect('offset_id',$_ENV['account']['reconcile_offset_id'],null,$this->AccountPairList)  . '</td></tr>';
    echo '<tr><td class="l" title="Which data format is this in?">Format:</td><td>' . $this->formSelect('format',null,null,Account_Reconcile::$format_list) . '</td></tr>';
    echo '<tr><td class="l">File:</td><td><input name="file" type="file">';
    echo ' <span class="s">(p:' . ini_get('post_max_size') . '/u:' . ini_get('upload_max_filesize') . ')</span>';
    echo '</td></tr>';
    echo '</table>';
    echo '<div class="cmd"><input name="cmd" type="submit" value="Upload" /></div>';
    echo '</fieldset>';
    echo '</form>';
    return(0);
}

