<?php
/**
    @todo Link this Account to A Customer
*/

echo $this->form('Account',array('action'=>$this->appurl.'/account/save','method'=>'post'));

echo '<div>' . $this->formHidden('id',$this->Account->id) . '</div>';

echo '<table>';

echo "<tr><td class='l'>Kind:</td><td colspan='2'>" . $this->formSelect('kind',$this->Account->kind,null,$this->AccountKindList) . "</td></tr>";
echo "<tr><td class='l'>Code &amp; Name:</td><td>" . $this->formText('code',$this->Account->code,array('size'=>6)) . "</td><td>" . $this->formText('name',$this->Account->name,array('size'=>40)) . "</td></tr>";

// Note
// echo "<tr><td class='b r'>Note:</td><td colspan='2'>" . $this->formText('note',$this->Account->note,array('size'=>40)) . "</td></tr>";

// Parent Account
$AccountList = array();
$AccountList[0] = '- None -';
foreach ($this->AccountList as $item) {

    if (!empty($item->parent_id)) continue;

	$AccountList[$item->id] = $item->full_name;
}
echo "<tr><td class='b r'>Parent:</td><td colspan='2'>" . $this->formSelect('parent_id',$this->Account->parent_id,null,$AccountList) . "</td></tr>";



/*
echo "<tr><td class='b r'>Type:</td><td><select name='flag_life'>";
foreach (array('Permanant'=>Account::PERMANENT,'Temporary'=>Account::TEMPORARY) as $k=>$v)
  echo "<option ".($a->flag&$v?"selected='selected' ":null)."value='$v'>$k</option>";
echo "</select><select name='flag_type'>";
foreach (array('Asset'=>Account::ASSET,'Liability'=>Account::LIABILITY,'Equity'=>Account::EQUITY,'Revenue'=>Account::REVENUE,'Expense'=>Account::EXPENSE) as $k=>$v)
  echo "<option ".($a->flag&$v?"selected='selected' ":null)."value='$v'>$k</option>";
echo "</select></td></tr>\n";

echo "<tr><td class='b r'>Class:</td><td><select name='flag_class'><option value='0'>None</option>";
foreach (array('Cash'=>Account::CASH,'Accounts Receiveable'=>Account::AR,'Accounts Payable'=>ACCOUNT::AP) as $k=>$v)
  echo "<option ".($a->flag&$v?"selected='selected' ":null)."value='$v'>$k</option>";
echo "</select><select name='flag_bank'><option value='0'>None</option>";
foreach (array('Checking'=>Account::CHECKING,'Savings'=>Account::SAVINGS,'Market'=>Account::MARKET) as $k=>$v)
  echo "<option ".($a->flag&$v?"selected='selected' ":null)."value='$v'>$k</option>";
echo "</select></td></tr>\n";
*/

$list = array();
$list[] = 'Sale of Goods or Services';
$list[] = 'Sale of Loans, Debt or Equity Instruments';
$list[] = 'Dividends Received on Equity Securities';
$list[] = 'Interest Received on Loans';

$list[] = 'Interest Payments';
$list[] = 'Payments to Suppliers';
$list[] = 'Payments to Employees';
$list[] = 'Payments to Tax';
$list[] = 'Payment for Sale of Loans, Debt or Equity Instruments';

$list = array();
$list[0] = 'None';
$list += $this->AccountTaxLineList;
echo "<tr><td class='b r'>Tax Line:</td><td colspan='3'>" . $this->formSelect('account_tax_line_id',$this->Account->account_tax_line_id,null,$list) . "</td>";

/*
// Asset Details
echo "<tr><td class='b r'>Opening Balance:</td><td>" . $imperiumForm->input('Account.code',am($opts,array('class'=>'tb','size'=>8))) . "</td></tr>";
*/

// Kind Bank Account Details
echo "<tr><td class='b r'>Transit:</td><td colspan='2'>" . $this->formText('bank_routing',$this->Account->bank_routing,array('size'=>10)) . "</td></tr>";
echo "<tr><td class='b r'>Account:</td><td colspan='2'>" . $this->formText('bank_account',$this->Account->bank_account,null,array('size'=>12)) . "</td></tr>";

echo '</table>';

/*
echo $imperiumForm->checkbox('Income Statement');
echo $imperiumForm->checkbox('Equity Statement');
echo $imperiumForm->checkbox('Balance Sheet');
echo $imperiumForm->checkbox('Cash Flow');
*/

echo '<div class="cmd">';
echo '<input name="cmd" type="submit" value="Save">';
echo '<input name="cmd" type="submit" value="Delete">';
echo '</div>';

echo '</form>';
