<?php
/**
	@file
	@brief Imperium Dashboard View
*/

$list = array_keys($this->data);
foreach ($list as $name) {

    if (!isset($this->data[$name])) {
        continue;
    }

    $info = $this->data[$name];

    if (count($info['list']) > 0)
    {
        // echo "<div style='display: table-cell;'>";
        echo '<div>'; // style='display: table-cell;'>";
        echo sprintf('<h2>%d %s</h2>',count($info['list']),$name);
        echo $this->partial($info['view'],array('list'=>$info['list'],'opts'=>array('head'=>true)));
        echo '</div>';
    }
}
