<?php
/**
    Imperium Login View

    Draws the Login Form

    @copyright      2008 Edoceo, Inc
    @package    edoceo-imperium
    @link       http://imperium.edoceo.com
    @since      File available since Release 1013

*/

echo '<form action="' . $this->link('/login') . '" method="post">';

//echo "<div>";
//echo "<input id='flash_enabled' name='flash_enabled' type='hidden' value='' />";
//echo "<input id='js_enabled' name='js_enabled' type='hidden' value='' />";
//echo "<input id='java_enabled' name='java_enabled' type='hidden' value='' />";
//echo "<input id='pdf_enabled' name='pdf_enabled' type='hidden' value='' />";
//echo "</div>";

//if (isset($_GET['r'])) echo "<input name='r' type='hidden' value='".$_GET['r']."' />\n";
echo '<table id="signin">';
echo '<tr><td class="l">Username:</td><td>' . $this->formText('username',null) . '</td></tr>';
echo '<tr><td class="l">Password:</td><td>' . $this->formPassword('password',null) .'</td></tr>';
echo '<tr><td class="l">Save 24h:</td><td><input name="s24" type="checkbox" value="1"></td></tr>'; 
echo '</table>';

echo '<div class="bf c"><input name="c" type="submit" value="Login"></div>';

echo '</form>';

